version: '3.3'

services:
  mygo-driver:
    privileged: true
    build:
        context: .
    ports:
      - '25000:25000'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1000M  